from performance_analyzer.typing_path.enum._editoperationtype import EditOperationType
from performance_analyzer.typing_path.enum._textchangetype import TextChangeType
from performance_analyzer.typing_path.enum._textchangeposition import TextChangePosition

